version: "3"
services:
  nginx-api-gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-api-gateway/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - product-service
      - order-service

  user-service:
    build: ./user-service
    volumes:
      - ./user-service:/app
    depends_on:
      - user-database
    environment:
      JWT_KEY: secret
  user-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 0.0.0.0:8002:3306

  product-service:
    build: ./product-service
    volumes:
      - ./product-service:/app
    depends_on:
      - product-database
    environment:
      JWT_KEY: secret
  product-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: products
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 0.0.0.0:8001:3306

  order-service:
    build: ./order-service
    volumes:
      - ./order-service:/app
    depends_on:
      - order-database
    environment:
      JWT_KEY: secret
      PRODUCT_SERVICE_BASE_URL: http://product-service:3000/
      PRODUCT_SERVICE_INTERNAL_BASE_URL: http://product-service:3001/
  order-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 0.0.0.0:8003:3306
